### ISSUE TITLE
Student model update

### ISSUE THREAD

**Issue by stricoff92** [andrewhylee/proj_2_pullUpClub#2]
Remove the Fields `pullUpCount` `record_date` from the `Student` model. `Student` model should only have information about a student.

- consider removing `email` and `age`. This is personal info you don't really need
- make `name` a required field
- slugs should be unique
- Maybe add a `nickname` field, or something similar. Think like how arcade games would show off high scores as 3 letter initials.

![image](https://user-images.githubusercontent.com/20848221/77809560-8e9f4880-7066-11ea-8c3e-256f3ce3fc46.png)

**Comment by andrewhylee** [comment]
I stumbled on all these fields and got too ecstatic.
I will calm myself.
Done!
