### ISSUE TITLE
PullUpSession model

### ISSUE THREAD

**Issue by stricoff92** [andrewhylee/proj_2_pullUpClub#3]
Create a model called `PullUpSession`. Instances of this model will represent 1 student doing 1 set of pullups. This model should have a foreign key field `student` that points back to the student who completed the pullups. Deleting a student should result in all their pullupsessions to be deleted.

![](https://media.giphy.com/media/gbPGNztPdhS6c/giphy.gif)

**Comment by andrewhylee** [comment]
Done and Done.
She gon'
