### ISSUE TITLE
Pull Up Session Tweaks

### ISSUE THREAD

**Issue by stricoff92** [andrewhylee/proj_2_pullUpClub#4]
- There's 1 more field that should be added to `PullUpSessions`. Hint: We're going to be creating graphs and stuff with this. 

- change field name `amount_of_pullups` to  `pullup_count`, or maybe just `count`. When dealing with integers or something you literally count, "count" usually sounds better (pull ups, product orders, tacos, etc). "Amount" usually sounds better for decimals (money, time etc).

- Dont allow negative pullup count

**Comment by andrewhylee** [comment]
Ok. Changes Made. Will send pull request.
I am assuming it is the time component missing in the `PullUpSessions` Model.
