### ISSUE TITLE
Base HTML Template

### ISSUE THREAD

**Issue by stricoff92** [andrewhylee/proj_2_pullUpClub#6]
Create a Base HTML template called `base.html` that includes `<html>` `<head>` and `<body>` tags. 
- Inside the head tag import bootstrap and jquery from a CDN.
- Inside the body tag create a block called `content`. All of the HTML templates you write will extent this base file and drop elements inside this `content` block.

**Comment by andrewhylee** [comment]
Ah this is easssssy :dancer:

**Comment by andrewhylee** [comment]
Hmmm I see a lot of ppl putting Bootstrap imports at the last part of the body tag?
